BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw CharmadaBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw TotartleBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw GentlarvaBitmasks
	dw PupalBitmasks
	dw CarapthorBitmasks
	dw KotoraBitmasks
	dw GaotoraBitmasks
	dw GorotoraBitmasks
	dw RaitoraBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw GorochuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw NidoreignBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpiiiBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw BittybatBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasporBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw CoinpurBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PerrserkerBitmasks
	dw PsyduckBitmasks
	dw WeirduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw AnnihilapeBitmasks
	dw PupperonBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw BellignanBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw ToedscoolBitmasks
	dw ToedscruelBitmasks
	dw BlottleBitmasks
	dw PendrakenBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw KoltaBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw BalumbaBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw GavillainBitmasks
	dw CheepBitmasks
	dw JabettaBitmasks
	dw RibbitoBitmasks
	dw CroakozunaBitmasks
	dw FarfetchDBitmasks
	dw LuxwanBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw SmujjBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw DisturbanBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw GuardiaBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw LickilickyBitmasks
	dw LickilordBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw HappinyBitmasks
	dw ChanseyBitmasks
	dw BurgelaBitmasks
	dw TangelaBitmasks
	dw TangrowthBitmasks
	dw JungelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw BlastykeBitmasks
	dw BlastoiseBitmasks
	dw OrfryBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MimeJrBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw KleavorBitmasks
	dw JynxBitmasks
	dw BuuBitmasks
	dw ElectabuzzBitmasks
	dw ElectivireBitmasks
	dw MagmarBitmasks
	dw MagmortarBitmasks
	dw PinsirBitmasks
	dw TriculesBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw MagipreyBitmasks
	dw TerradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw MimmeoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw FeradactylBitmasks
	dw AerodactylBitmasks
	dw DecillaBitmasks
	dw GawarhedBitmasks
	dw MunchlaxBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw SqueamataBitmasks
	dw MinistareBitmasks
	dw IguanarchBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw CubburnBitmasks
	dw FlambearBitmasks
	dw BruinousBitmasks
	dw PalssioBitmasks
	dw PressioBitmasks
	dw DonmarinBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw FolageBitmasks
	dw BarreauBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw ReroadBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw NatuBitmasks
	dw QatuBitmasks
	dw XatuBitmasks
	dw MoibelleBitmasks
	dw BelledamBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw AzurillBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw BonslyBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw AmbipomBitmasks
	dw SunkernBitmasks
	dw SunbudBitmasks
	dw SunfloraBitmasks
	dw HippunkBitmasks
	dw AercrowBitmasks
	dw FoxfireBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw Pending03Bitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw StromenBitmasks
	dw PhandarinBitmasks
	dw UnownBitmasks
	dw WynautBitmasks
	dw WobbuffetBitmasks
	dw BipullaBitmasks
	dw GirafarigBitmasks
	dw FarigirafBitmasks
	dw EmordromeBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw DudunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw CaretorkerBitmasks
	dw QwilfishBitmasks
	dw KazappelinBitmasks
	dw QwilfatherBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw PockleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw UrsalunaBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw HirsuswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw StricheelBitmasks
	dw LurreelBitmasks
	dw DelibirdBitmasks
	dw MantykeBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw SmeargleBitmasks
	dw GrenmarBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElebebiBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	
	dw WaruchuBitmasks
	dw SoneggBitmasks
	dw CacawphonyBitmasks
	dw TrebirBitmasks
	dw SakurazeBitmasks
	dw TanobiBitmasks
	dw TrustanBitmasks
	dw KuwaguardBitmasks
	dw TonquitoBitmasks
	dw MolambinoBitmasks
	dw LuanboBitmasks
	dw GranboBitmasks
	dw AngoreBitmasks
	dw EucalaBitmasks
	dw KiwookedBitmasks
	dw CyclorpBitmasks
	dw KitsenBitmasks
	dw WispiritBitmasks
	dw CoatlBitmasks
	dw MimearBitmasks
	dw InoshikaBitmasks
	dw RuddernautBitmasks
	dw XylodonBitmasks
	dw XylofinBitmasks
	dw DokuroarBitmasks
	dw ScreamTailBitmasks
	dw SandyShocksBitmasks
	dw GreatTuskBitmasks
	dw FlutterManeBitmasks
	dw IronTreadsBitmasks
	dw IronBundleBitmasks
	dw IronThornsBitmasks
	
	dw RagingBoltBitmasks
	dw GougingFireBitmasks
	dw WalkingWakeBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw KomainuBitmasks
	dw CelebiBitmasks
	assert_table_length NUM_POKEMON
