FramesPointers:
	table_width 3, FramesPointers
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba TotartleFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba GentlarvaFrames
	dba PupalFrames
	dba CarapthorFrames
	dba KotoraFrames
	dba GaotoraFrames
	dba GorotoraFrames
	dba RaitoraFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba RattataFrames
	dba RaticateFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba GorochuFrames
	dba SandshrewFrames
	dba SandslashFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba NidoreignFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpiiiFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba BittybatFrames
	dba ZubatFrames
	dba GolbatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasporFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba CoinpurFrames
	dba MeowthFrames
	dba PersianFrames
	dba PerrserkerFrames
	dba PsyduckFrames
	dba WeirduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba AnnihilapeFrames
	dba PupperonFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba BellignanFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba CheepFrames
	dba JabettaFrames
	dba RibbitoFrames
	dba CroakozunaFrames
	dba FarfetchDFrames
	dba LuxwanFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba ShellderFrames
	dba CloysterFrames
	dba DisturbanFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba LickitungFrames
	dba LickilickyFrames
	dba LickilordFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba BurgelaFrames
	dba TangelaFrames
	dba TangrowthFrames
	dba JungelaFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba BlastykeFrames
	dba BlastoiseFrames
	dba OrfryFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba MrMimeFrames
	dba ScytherFrames
	dba KleavorFrames
	dba JynxFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba PinsirFrames
	dba TriculesFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba MunchlaxFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba CubburnFrames
	dba FlambearFrames
	dba BruinousFrames
	dba PalssioFrames
	dba PressioFrames
	dba DonmarinFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba LedybaFrames
	dba LedianFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba FolageFrames
	dba BarreauFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba ReroadFrames
	dba PichuFrames
	dba CleffaFrames
	dba IgglybuffFrames
	dba TogepiFrames
	dba TogeticFrames
	dba TogekissFrames
	dba NatuFrames
	dba QatuFrames
	dba XatuFrames
	dba MoibelleFrames
	dba BelledamFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba BellossomFrames
	dba AzurillFrames
	dba MarillFrames
	dba AzumarillFrames
	dba SudowoodoFrames
	dba PolitoedFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba AipomFrames
	dba AmbipomFrames
	dba SunkernFrames
	dba SunbudFrames
	dba SunfloraFrames
	dba HippunkFrames
	dba AercrowFrames
	dba FoxfireFrames
	dba YanmaFrames
	dba YanmegaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba LeafeonFrames
	dba GlaceonFrames
	dba SylveonFrames
	dba MurkrowFrames
	dba SlowkingFrames
	dba MisdreavusFrames
	dba MismagiusFrames
	dba StromenFrames
	dba PhandarinFrames
	dba UnownFrames
	dba WynautFrames
	dba WobbuffetFrames
	dba BipullaFrames
	dba CalflacFrames
	dba GirafarigFrames
	dba FarigirafFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba DudunsparceFrames
	dba GligarFrames
	dba SteelixFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba KazeppelinFrames
	dba QwilfatherFrames
	dba ScizorFrames
	dba ShuckleFrames
	dba PockleFrames
	dba HeracrossFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba UrsalunaFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba CorsolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba StricheelFrames
	dba LurreelFrames
	dba DelibirdFrames
	dba MantykeFrames
	dba MantineFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba KingdraFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba Porygon2Frames
	dba StantlerFrames
	dba SmeargleFrames
	dba TyrogueFrames
	dba HitmontopFrames
	dba SmoochumFrames
	dba ElekidFrames
	dba MagbyFrames
	dba MiltankFrames
	dba BlisseyFrames
	
	dba WaruchuFrames
	dba SoneggFrames
	dba CacawphonyFrames
	dba TrebirFrames
	dba SakurazeFrames
	dba AmanobiFrames
	dba TrustanFrames
	dba KuwaguardFrames
	dba TonquitoFrames
	dba MolambinoFrames
	dba LuanboFrames
	dba GranboFrames
	dba AngoreFrames
	dba EucalaFrames
	dba KiwookedFrames
	dba CyclorpFrames
	dba KitsenFrames
	dba WispiritFrames
	dba CoatlFrames
	dba MimearFrames
	dba InoshikaFrames
	dba RuddernautFrames
	dba XylodonFrames
	dba XylofinFrames
	dba DokuroarFrames
	dba ScreamTailFrames
	dba SandyShocksFrames
	dba GreatTuskFrames
	dba FlutterManeFrames
	dba IronTreadsFrames
	dba IronBundleFrames
	dba IronThornsFrames
	
	dba RagingBoltFrames
	dba GougingFireFrames
	dba WalkingWakeFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba ShiShiFrames
	dba CelebiFrames
	assert_table_length NUM_POKEMON
