AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw TotartleAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw GentlarvaAnimationIdle
	dw PupalAnimationIdle
	dw CarapthorAnimationIdle
	dw KotoraAnimationIdle
	dw GaotoraAnimationIdle
	dw GorotoraAnimationIdle
	dw RaitoraAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw GorochuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw NidoreignAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpiiiAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw BittybatAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasporAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw CoinpurAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PerrserkerAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw AnnihilapeAnimationIdle
	dw PupperonAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw BellignanAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw LickilickyAnimationIdle
	dw LickilordAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw BurgelaAnimationIdle
	dw TangelaAnimationIdle
	dw TangrowthAnimationIdle
	dw JungelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw BlastykeAnimationIdle
	dw BlastoiseAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw KleavorAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TriculesAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw MunchlaxAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw CubburnAnimationIdle
	dw FlambearAnimationIdle
	dw BruinousAnimationIdle
	dw PalssioAnimationIdle
	dw PressioAnimationIdle
	dw DonmarinAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw FolageAnimationIdle
	dw BarreauAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MoibelleAnimationIdle
	dw BelledamAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw AercrowAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw SylveonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw StromenAnimationIdle
	dw PhandarinAnimationIdle
	dw UnownAnimationIdle
	dw WynautAnimationIdle
	dw WobbuffetAnimationIdle
	dw BipullaAnimationIdle
	dw CalflacAnimationIdle
	dw GirafarigAnimationIdle
	dw FarigirafAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw DudunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw PockleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw UrsalunaAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	
	dw WaruchuAnimationIdle
	dw SoneggAnimationIdle
	dw CacawphonyAnimationIdle
	dw TrebirAnimationIdle
	dw SakurazeAnimationIdle
	dw AmanobiAnimationIdle
	dw TrustanAnimationIdle
	dw KuwaguardAnimationIdle
	dw TonquitoAnimationIdle
	dw MolambinoAnimationIdle
	dw LuanboAnimationIdle
	dw GranboAnimationIdle
	dw AngoreAnimationIdle
	dw EucalaAnimationIdle
	dw KiwookedAnimationIdle
	dw CyclorpAnimationIdle
	dw KitsenAnimationIdle
	dw WispiritAnimationIdle
	dw CoatlAnimationIdle
	dw MimearAnimationIdle
	dw InoshikaAnimationIdle
	dw RuddernautAnimationIdle
	dw XylodonAnimationIdle
	dw XylofinAnimationIdle
	dw DokuroarAnimationIdle
	dw ScreamTailAnimationIdle
	dw SandyShocksAnimationIdle
	dw GreatTuskAnimationIdle
	dw FlutterManeAnimationIdle
	dw IronTreadsAnimationIdle
	dw IronBundleAnimationIdle
	dw IronThornsAnimationIdle
	dw RagingBoltAnimationIdle
	dw GougingFireAnimationIdle
	dw WalkingWakeAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw ShiShiAnimationIdle
	dw CelebiAnimationIdle
	assert_table_length NUM_POKEMON
